// Generated by CoffeeScript 1.6.3
(function() {
  var UpdateClient, io, _;

  _ = require('underscore');

  io = require('socket.io-client');

  UpdateClient = function(server, opts) {
    var client;
    client = {};
    client.watches = {};
    client.socket = io.connect(server, opts);
    client.socket.on('connect', function() {
      return console.log("socket connected");
    });
    client.socket.on('update', function(data) {
      return client.watches[data.path].callback.apply({}, arguments);
    });
    client.watch = function(details, callback) {
      client.watches[details.path] = {
        details: details,
        callback: callback
      };
      return client.socket.emit('watch', details);
    };
    client.socket.on('disconnect', function() {
      return console.log("ouch! socket diconnected");
    });
    return client;
  };

}).call(this);
